# SPDX-FileCopyrightText: 2023 Alex Turbov <zaufi@pm.me>
# SPDX-License-Identifier: CC0-1.0
name: Checking `pre-commit` hooks

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  # enable this workflow to be reused
  workflow_call:

jobs:
  pre-commit-checks:
    name: Checking `pre-commit` hooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checking configured hooks
        uses: pre-commit/action@v3.0.0
